package valpoSystems.emailTask.orm.model;

import java.util.Date;

public class AuditTaskImpl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.id
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.activationtime
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Date activationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.actualowner
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String actualowner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.createdby
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.createdon
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Date createdon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.deploymentid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String deploymentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.description
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.duedate
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Date duedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.name
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.parentid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Long parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.priority
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.processid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String processid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.processinstanceid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Long processinstanceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.processsessionid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Long processsessionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.status
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.taskid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Long taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.workitemid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Long workitemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audittaskimpl.lastmodificationdate
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Date lastmodificationdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.id
     *
     * @return the value of public.audittaskimpl.id
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.id
     *
     * @param id the value for public.audittaskimpl.id
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.activationtime
     *
     * @return the value of public.audittaskimpl.activationtime
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Date getActivationtime() {
        return activationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.activationtime
     *
     * @param activationtime the value for public.audittaskimpl.activationtime
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setActivationtime(Date activationtime) {
        this.activationtime = activationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.actualowner
     *
     * @return the value of public.audittaskimpl.actualowner
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getActualowner() {
        return actualowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.actualowner
     *
     * @param actualowner the value for public.audittaskimpl.actualowner
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setActualowner(String actualowner) {
        this.actualowner = actualowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.createdby
     *
     * @return the value of public.audittaskimpl.createdby
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.createdby
     *
     * @param createdby the value for public.audittaskimpl.createdby
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.createdon
     *
     * @return the value of public.audittaskimpl.createdon
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Date getCreatedon() {
        return createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.createdon
     *
     * @param createdon the value for public.audittaskimpl.createdon
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.deploymentid
     *
     * @return the value of public.audittaskimpl.deploymentid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getDeploymentid() {
        return deploymentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.deploymentid
     *
     * @param deploymentid the value for public.audittaskimpl.deploymentid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setDeploymentid(String deploymentid) {
        this.deploymentid = deploymentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.description
     *
     * @return the value of public.audittaskimpl.description
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.description
     *
     * @param description the value for public.audittaskimpl.description
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.duedate
     *
     * @return the value of public.audittaskimpl.duedate
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Date getDuedate() {
        return duedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.duedate
     *
     * @param duedate the value for public.audittaskimpl.duedate
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.name
     *
     * @return the value of public.audittaskimpl.name
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.name
     *
     * @param name the value for public.audittaskimpl.name
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.parentid
     *
     * @return the value of public.audittaskimpl.parentid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.parentid
     *
     * @param parentid the value for public.audittaskimpl.parentid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.priority
     *
     * @return the value of public.audittaskimpl.priority
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.priority
     *
     * @param priority the value for public.audittaskimpl.priority
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.processid
     *
     * @return the value of public.audittaskimpl.processid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.processid
     *
     * @param processid the value for public.audittaskimpl.processid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setProcessid(String processid) {
        this.processid = processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.processinstanceid
     *
     * @return the value of public.audittaskimpl.processinstanceid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Long getProcessinstanceid() {
        return processinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.processinstanceid
     *
     * @param processinstanceid the value for public.audittaskimpl.processinstanceid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setProcessinstanceid(Long processinstanceid) {
        this.processinstanceid = processinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.processsessionid
     *
     * @return the value of public.audittaskimpl.processsessionid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Long getProcesssessionid() {
        return processsessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.processsessionid
     *
     * @param processsessionid the value for public.audittaskimpl.processsessionid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setProcesssessionid(Long processsessionid) {
        this.processsessionid = processsessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.status
     *
     * @return the value of public.audittaskimpl.status
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.status
     *
     * @param status the value for public.audittaskimpl.status
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.taskid
     *
     * @return the value of public.audittaskimpl.taskid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Long getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.taskid
     *
     * @param taskid the value for public.audittaskimpl.taskid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setTaskid(Long taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.workitemid
     *
     * @return the value of public.audittaskimpl.workitemid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Long getWorkitemid() {
        return workitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.workitemid
     *
     * @param workitemid the value for public.audittaskimpl.workitemid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setWorkitemid(Long workitemid) {
        this.workitemid = workitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audittaskimpl.lastmodificationdate
     *
     * @return the value of public.audittaskimpl.lastmodificationdate
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Date getLastmodificationdate() {
        return lastmodificationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audittaskimpl.lastmodificationdate
     *
     * @param lastmodificationdate the value for public.audittaskimpl.lastmodificationdate
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setLastmodificationdate(Date lastmodificationdate) {
        this.lastmodificationdate = lastmodificationdate;
    }
}