package valpoSystems.emailTask.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AuditTaskImplExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public AuditTaskImplExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andActivationtimeIsNull() {
            addCriterion("activationtime is null");
            return (Criteria) this;
        }

        public Criteria andActivationtimeIsNotNull() {
            addCriterion("activationtime is not null");
            return (Criteria) this;
        }

        public Criteria andActivationtimeEqualTo(Date value) {
            addCriterion("activationtime =", value, "activationtime");
            return (Criteria) this;
        }

        public Criteria andActivationtimeNotEqualTo(Date value) {
            addCriterion("activationtime <>", value, "activationtime");
            return (Criteria) this;
        }

        public Criteria andActivationtimeGreaterThan(Date value) {
            addCriterion("activationtime >", value, "activationtime");
            return (Criteria) this;
        }

        public Criteria andActivationtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("activationtime >=", value, "activationtime");
            return (Criteria) this;
        }

        public Criteria andActivationtimeLessThan(Date value) {
            addCriterion("activationtime <", value, "activationtime");
            return (Criteria) this;
        }

        public Criteria andActivationtimeLessThanOrEqualTo(Date value) {
            addCriterion("activationtime <=", value, "activationtime");
            return (Criteria) this;
        }

        public Criteria andActivationtimeIn(List<Date> values) {
            addCriterion("activationtime in", values, "activationtime");
            return (Criteria) this;
        }

        public Criteria andActivationtimeNotIn(List<Date> values) {
            addCriterion("activationtime not in", values, "activationtime");
            return (Criteria) this;
        }

        public Criteria andActivationtimeBetween(Date value1, Date value2) {
            addCriterion("activationtime between", value1, value2, "activationtime");
            return (Criteria) this;
        }

        public Criteria andActivationtimeNotBetween(Date value1, Date value2) {
            addCriterion("activationtime not between", value1, value2, "activationtime");
            return (Criteria) this;
        }

        public Criteria andActualownerIsNull() {
            addCriterion("actualowner is null");
            return (Criteria) this;
        }

        public Criteria andActualownerIsNotNull() {
            addCriterion("actualowner is not null");
            return (Criteria) this;
        }

        public Criteria andActualownerEqualTo(String value) {
            addCriterion("actualowner =", value, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerNotEqualTo(String value) {
            addCriterion("actualowner <>", value, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerGreaterThan(String value) {
            addCriterion("actualowner >", value, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerGreaterThanOrEqualTo(String value) {
            addCriterion("actualowner >=", value, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerLessThan(String value) {
            addCriterion("actualowner <", value, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerLessThanOrEqualTo(String value) {
            addCriterion("actualowner <=", value, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerLike(String value) {
            addCriterion("actualowner like", value, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerNotLike(String value) {
            addCriterion("actualowner not like", value, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerIn(List<String> values) {
            addCriterion("actualowner in", values, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerNotIn(List<String> values) {
            addCriterion("actualowner not in", values, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerBetween(String value1, String value2) {
            addCriterion("actualowner between", value1, value2, "actualowner");
            return (Criteria) this;
        }

        public Criteria andActualownerNotBetween(String value1, String value2) {
            addCriterion("actualowner not between", value1, value2, "actualowner");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNull() {
            addCriterion("createdby is null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNotNull() {
            addCriterion("createdby is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyEqualTo(String value) {
            addCriterion("createdby =", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotEqualTo(String value) {
            addCriterion("createdby <>", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThan(String value) {
            addCriterion("createdby >", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
            addCriterion("createdby >=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThan(String value) {
            addCriterion("createdby <", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThanOrEqualTo(String value) {
            addCriterion("createdby <=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLike(String value) {
            addCriterion("createdby like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotLike(String value) {
            addCriterion("createdby not like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIn(List<String> values) {
            addCriterion("createdby in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotIn(List<String> values) {
            addCriterion("createdby not in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyBetween(String value1, String value2) {
            addCriterion("createdby between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotBetween(String value1, String value2) {
            addCriterion("createdby not between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedonIsNull() {
            addCriterion("createdon is null");
            return (Criteria) this;
        }

        public Criteria andCreatedonIsNotNull() {
            addCriterion("createdon is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedonEqualTo(Date value) {
            addCriterion("createdon =", value, "createdon");
            return (Criteria) this;
        }

        public Criteria andCreatedonNotEqualTo(Date value) {
            addCriterion("createdon <>", value, "createdon");
            return (Criteria) this;
        }

        public Criteria andCreatedonGreaterThan(Date value) {
            addCriterion("createdon >", value, "createdon");
            return (Criteria) this;
        }

        public Criteria andCreatedonGreaterThanOrEqualTo(Date value) {
            addCriterion("createdon >=", value, "createdon");
            return (Criteria) this;
        }

        public Criteria andCreatedonLessThan(Date value) {
            addCriterion("createdon <", value, "createdon");
            return (Criteria) this;
        }

        public Criteria andCreatedonLessThanOrEqualTo(Date value) {
            addCriterion("createdon <=", value, "createdon");
            return (Criteria) this;
        }

        public Criteria andCreatedonIn(List<Date> values) {
            addCriterion("createdon in", values, "createdon");
            return (Criteria) this;
        }

        public Criteria andCreatedonNotIn(List<Date> values) {
            addCriterion("createdon not in", values, "createdon");
            return (Criteria) this;
        }

        public Criteria andCreatedonBetween(Date value1, Date value2) {
            addCriterion("createdon between", value1, value2, "createdon");
            return (Criteria) this;
        }

        public Criteria andCreatedonNotBetween(Date value1, Date value2) {
            addCriterion("createdon not between", value1, value2, "createdon");
            return (Criteria) this;
        }

        public Criteria andDeploymentidIsNull() {
            addCriterion("deploymentid is null");
            return (Criteria) this;
        }

        public Criteria andDeploymentidIsNotNull() {
            addCriterion("deploymentid is not null");
            return (Criteria) this;
        }

        public Criteria andDeploymentidEqualTo(String value) {
            addCriterion("deploymentid =", value, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidNotEqualTo(String value) {
            addCriterion("deploymentid <>", value, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidGreaterThan(String value) {
            addCriterion("deploymentid >", value, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidGreaterThanOrEqualTo(String value) {
            addCriterion("deploymentid >=", value, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidLessThan(String value) {
            addCriterion("deploymentid <", value, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidLessThanOrEqualTo(String value) {
            addCriterion("deploymentid <=", value, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidLike(String value) {
            addCriterion("deploymentid like", value, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidNotLike(String value) {
            addCriterion("deploymentid not like", value, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidIn(List<String> values) {
            addCriterion("deploymentid in", values, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidNotIn(List<String> values) {
            addCriterion("deploymentid not in", values, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidBetween(String value1, String value2) {
            addCriterion("deploymentid between", value1, value2, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDeploymentidNotBetween(String value1, String value2) {
            addCriterion("deploymentid not between", value1, value2, "deploymentid");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDuedateIsNull() {
            addCriterion("duedate is null");
            return (Criteria) this;
        }

        public Criteria andDuedateIsNotNull() {
            addCriterion("duedate is not null");
            return (Criteria) this;
        }

        public Criteria andDuedateEqualTo(Date value) {
            addCriterion("duedate =", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateNotEqualTo(Date value) {
            addCriterion("duedate <>", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateGreaterThan(Date value) {
            addCriterion("duedate >", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateGreaterThanOrEqualTo(Date value) {
            addCriterion("duedate >=", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateLessThan(Date value) {
            addCriterion("duedate <", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateLessThanOrEqualTo(Date value) {
            addCriterion("duedate <=", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateIn(List<Date> values) {
            addCriterion("duedate in", values, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateNotIn(List<Date> values) {
            addCriterion("duedate not in", values, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateBetween(Date value1, Date value2) {
            addCriterion("duedate between", value1, value2, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateNotBetween(Date value1, Date value2) {
            addCriterion("duedate not between", value1, value2, "duedate");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("parentid is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("parentid is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(Long value) {
            addCriterion("parentid =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(Long value) {
            addCriterion("parentid <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(Long value) {
            addCriterion("parentid >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(Long value) {
            addCriterion("parentid >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(Long value) {
            addCriterion("parentid <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(Long value) {
            addCriterion("parentid <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<Long> values) {
            addCriterion("parentid in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<Long> values) {
            addCriterion("parentid not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(Long value1, Long value2) {
            addCriterion("parentid between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(Long value1, Long value2) {
            addCriterion("parentid not between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("priority is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("priority is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("priority =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("priority <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("priority >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("priority >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("priority <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("priority <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("priority in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("priority not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("priority between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("priority not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andProcessidIsNull() {
            addCriterion("processid is null");
            return (Criteria) this;
        }

        public Criteria andProcessidIsNotNull() {
            addCriterion("processid is not null");
            return (Criteria) this;
        }

        public Criteria andProcessidEqualTo(String value) {
            addCriterion("processid =", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotEqualTo(String value) {
            addCriterion("processid <>", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidGreaterThan(String value) {
            addCriterion("processid >", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidGreaterThanOrEqualTo(String value) {
            addCriterion("processid >=", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLessThan(String value) {
            addCriterion("processid <", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLessThanOrEqualTo(String value) {
            addCriterion("processid <=", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLike(String value) {
            addCriterion("processid like", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotLike(String value) {
            addCriterion("processid not like", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidIn(List<String> values) {
            addCriterion("processid in", values, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotIn(List<String> values) {
            addCriterion("processid not in", values, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidBetween(String value1, String value2) {
            addCriterion("processid between", value1, value2, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotBetween(String value1, String value2) {
            addCriterion("processid not between", value1, value2, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidIsNull() {
            addCriterion("processinstanceid is null");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidIsNotNull() {
            addCriterion("processinstanceid is not null");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidEqualTo(Long value) {
            addCriterion("processinstanceid =", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidNotEqualTo(Long value) {
            addCriterion("processinstanceid <>", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidGreaterThan(Long value) {
            addCriterion("processinstanceid >", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidGreaterThanOrEqualTo(Long value) {
            addCriterion("processinstanceid >=", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidLessThan(Long value) {
            addCriterion("processinstanceid <", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidLessThanOrEqualTo(Long value) {
            addCriterion("processinstanceid <=", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidIn(List<Long> values) {
            addCriterion("processinstanceid in", values, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidNotIn(List<Long> values) {
            addCriterion("processinstanceid not in", values, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidBetween(Long value1, Long value2) {
            addCriterion("processinstanceid between", value1, value2, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidNotBetween(Long value1, Long value2) {
            addCriterion("processinstanceid not between", value1, value2, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidIsNull() {
            addCriterion("processsessionid is null");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidIsNotNull() {
            addCriterion("processsessionid is not null");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidEqualTo(Long value) {
            addCriterion("processsessionid =", value, "processsessionid");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidNotEqualTo(Long value) {
            addCriterion("processsessionid <>", value, "processsessionid");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidGreaterThan(Long value) {
            addCriterion("processsessionid >", value, "processsessionid");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidGreaterThanOrEqualTo(Long value) {
            addCriterion("processsessionid >=", value, "processsessionid");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidLessThan(Long value) {
            addCriterion("processsessionid <", value, "processsessionid");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidLessThanOrEqualTo(Long value) {
            addCriterion("processsessionid <=", value, "processsessionid");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidIn(List<Long> values) {
            addCriterion("processsessionid in", values, "processsessionid");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidNotIn(List<Long> values) {
            addCriterion("processsessionid not in", values, "processsessionid");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidBetween(Long value1, Long value2) {
            addCriterion("processsessionid between", value1, value2, "processsessionid");
            return (Criteria) this;
        }

        public Criteria andProcesssessionidNotBetween(Long value1, Long value2) {
            addCriterion("processsessionid not between", value1, value2, "processsessionid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTaskidIsNull() {
            addCriterion("taskid is null");
            return (Criteria) this;
        }

        public Criteria andTaskidIsNotNull() {
            addCriterion("taskid is not null");
            return (Criteria) this;
        }

        public Criteria andTaskidEqualTo(Long value) {
            addCriterion("taskid =", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotEqualTo(Long value) {
            addCriterion("taskid <>", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidGreaterThan(Long value) {
            addCriterion("taskid >", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidGreaterThanOrEqualTo(Long value) {
            addCriterion("taskid >=", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidLessThan(Long value) {
            addCriterion("taskid <", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidLessThanOrEqualTo(Long value) {
            addCriterion("taskid <=", value, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidIn(List<Long> values) {
            addCriterion("taskid in", values, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotIn(List<Long> values) {
            addCriterion("taskid not in", values, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidBetween(Long value1, Long value2) {
            addCriterion("taskid between", value1, value2, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotBetween(Long value1, Long value2) {
            addCriterion("taskid not between", value1, value2, "taskid");
            return (Criteria) this;
        }

        public Criteria andWorkitemidIsNull() {
            addCriterion("workitemid is null");
            return (Criteria) this;
        }

        public Criteria andWorkitemidIsNotNull() {
            addCriterion("workitemid is not null");
            return (Criteria) this;
        }

        public Criteria andWorkitemidEqualTo(Long value) {
            addCriterion("workitemid =", value, "workitemid");
            return (Criteria) this;
        }

        public Criteria andWorkitemidNotEqualTo(Long value) {
            addCriterion("workitemid <>", value, "workitemid");
            return (Criteria) this;
        }

        public Criteria andWorkitemidGreaterThan(Long value) {
            addCriterion("workitemid >", value, "workitemid");
            return (Criteria) this;
        }

        public Criteria andWorkitemidGreaterThanOrEqualTo(Long value) {
            addCriterion("workitemid >=", value, "workitemid");
            return (Criteria) this;
        }

        public Criteria andWorkitemidLessThan(Long value) {
            addCriterion("workitemid <", value, "workitemid");
            return (Criteria) this;
        }

        public Criteria andWorkitemidLessThanOrEqualTo(Long value) {
            addCriterion("workitemid <=", value, "workitemid");
            return (Criteria) this;
        }

        public Criteria andWorkitemidIn(List<Long> values) {
            addCriterion("workitemid in", values, "workitemid");
            return (Criteria) this;
        }

        public Criteria andWorkitemidNotIn(List<Long> values) {
            addCriterion("workitemid not in", values, "workitemid");
            return (Criteria) this;
        }

        public Criteria andWorkitemidBetween(Long value1, Long value2) {
            addCriterion("workitemid between", value1, value2, "workitemid");
            return (Criteria) this;
        }

        public Criteria andWorkitemidNotBetween(Long value1, Long value2) {
            addCriterion("workitemid not between", value1, value2, "workitemid");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateIsNull() {
            addCriterion("lastmodificationdate is null");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateIsNotNull() {
            addCriterion("lastmodificationdate is not null");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateEqualTo(Date value) {
            addCriterion("lastmodificationdate =", value, "lastmodificationdate");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateNotEqualTo(Date value) {
            addCriterion("lastmodificationdate <>", value, "lastmodificationdate");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateGreaterThan(Date value) {
            addCriterion("lastmodificationdate >", value, "lastmodificationdate");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateGreaterThanOrEqualTo(Date value) {
            addCriterion("lastmodificationdate >=", value, "lastmodificationdate");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateLessThan(Date value) {
            addCriterion("lastmodificationdate <", value, "lastmodificationdate");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateLessThanOrEqualTo(Date value) {
            addCriterion("lastmodificationdate <=", value, "lastmodificationdate");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateIn(List<Date> values) {
            addCriterion("lastmodificationdate in", values, "lastmodificationdate");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateNotIn(List<Date> values) {
            addCriterion("lastmodificationdate not in", values, "lastmodificationdate");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateBetween(Date value1, Date value2) {
            addCriterion("lastmodificationdate between", value1, value2, "lastmodificationdate");
            return (Criteria) this;
        }

        public Criteria andLastmodificationdateNotBetween(Date value1, Date value2) {
            addCriterion("lastmodificationdate not between", value1, value2, "lastmodificationdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 07 01:42:26 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}