package valpoSystems.emailTask.orm.model;

import java.util.Date;

public class VariableInstanceLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.variableinstancelog.id
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.variableinstancelog.log_date
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Date logDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.variableinstancelog.externalid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String externalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.variableinstancelog.oldvalue
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String oldvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.variableinstancelog.processid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String processid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.variableinstancelog.processinstanceid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private Long processinstanceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.variableinstancelog.value
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.variableinstancelog.variableid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String variableid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.variableinstancelog.variableinstanceid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    private String variableinstanceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.variableinstancelog.id
     *
     * @return the value of public.variableinstancelog.id
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.variableinstancelog.id
     *
     * @param id the value for public.variableinstancelog.id
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.variableinstancelog.log_date
     *
     * @return the value of public.variableinstancelog.log_date
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.variableinstancelog.log_date
     *
     * @param logDate the value for public.variableinstancelog.log_date
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.variableinstancelog.externalid
     *
     * @return the value of public.variableinstancelog.externalid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getExternalid() {
        return externalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.variableinstancelog.externalid
     *
     * @param externalid the value for public.variableinstancelog.externalid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setExternalid(String externalid) {
        this.externalid = externalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.variableinstancelog.oldvalue
     *
     * @return the value of public.variableinstancelog.oldvalue
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getOldvalue() {
        return oldvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.variableinstancelog.oldvalue
     *
     * @param oldvalue the value for public.variableinstancelog.oldvalue
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setOldvalue(String oldvalue) {
        this.oldvalue = oldvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.variableinstancelog.processid
     *
     * @return the value of public.variableinstancelog.processid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.variableinstancelog.processid
     *
     * @param processid the value for public.variableinstancelog.processid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setProcessid(String processid) {
        this.processid = processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.variableinstancelog.processinstanceid
     *
     * @return the value of public.variableinstancelog.processinstanceid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Long getProcessinstanceid() {
        return processinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.variableinstancelog.processinstanceid
     *
     * @param processinstanceid the value for public.variableinstancelog.processinstanceid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setProcessinstanceid(Long processinstanceid) {
        this.processinstanceid = processinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.variableinstancelog.value
     *
     * @return the value of public.variableinstancelog.value
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.variableinstancelog.value
     *
     * @param value the value for public.variableinstancelog.value
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.variableinstancelog.variableid
     *
     * @return the value of public.variableinstancelog.variableid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getVariableid() {
        return variableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.variableinstancelog.variableid
     *
     * @param variableid the value for public.variableinstancelog.variableid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setVariableid(String variableid) {
        this.variableid = variableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.variableinstancelog.variableinstanceid
     *
     * @return the value of public.variableinstancelog.variableinstanceid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getVariableinstanceid() {
        return variableinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.variableinstancelog.variableinstanceid
     *
     * @param variableinstanceid the value for public.variableinstancelog.variableinstanceid
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setVariableinstanceid(String variableinstanceid) {
        this.variableinstanceid = variableinstanceid;
    }
}