package valpoSystems.emailTask.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VariableInstanceLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public VariableInstanceLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLogDateIsNull() {
            addCriterion("log_date is null");
            return (Criteria) this;
        }

        public Criteria andLogDateIsNotNull() {
            addCriterion("log_date is not null");
            return (Criteria) this;
        }

        public Criteria andLogDateEqualTo(Date value) {
            addCriterion("log_date =", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotEqualTo(Date value) {
            addCriterion("log_date <>", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateGreaterThan(Date value) {
            addCriterion("log_date >", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateGreaterThanOrEqualTo(Date value) {
            addCriterion("log_date >=", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLessThan(Date value) {
            addCriterion("log_date <", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLessThanOrEqualTo(Date value) {
            addCriterion("log_date <=", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateIn(List<Date> values) {
            addCriterion("log_date in", values, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotIn(List<Date> values) {
            addCriterion("log_date not in", values, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateBetween(Date value1, Date value2) {
            addCriterion("log_date between", value1, value2, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotBetween(Date value1, Date value2) {
            addCriterion("log_date not between", value1, value2, "logDate");
            return (Criteria) this;
        }

        public Criteria andExternalidIsNull() {
            addCriterion("externalid is null");
            return (Criteria) this;
        }

        public Criteria andExternalidIsNotNull() {
            addCriterion("externalid is not null");
            return (Criteria) this;
        }

        public Criteria andExternalidEqualTo(String value) {
            addCriterion("externalid =", value, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidNotEqualTo(String value) {
            addCriterion("externalid <>", value, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidGreaterThan(String value) {
            addCriterion("externalid >", value, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidGreaterThanOrEqualTo(String value) {
            addCriterion("externalid >=", value, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidLessThan(String value) {
            addCriterion("externalid <", value, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidLessThanOrEqualTo(String value) {
            addCriterion("externalid <=", value, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidLike(String value) {
            addCriterion("externalid like", value, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidNotLike(String value) {
            addCriterion("externalid not like", value, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidIn(List<String> values) {
            addCriterion("externalid in", values, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidNotIn(List<String> values) {
            addCriterion("externalid not in", values, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidBetween(String value1, String value2) {
            addCriterion("externalid between", value1, value2, "externalid");
            return (Criteria) this;
        }

        public Criteria andExternalidNotBetween(String value1, String value2) {
            addCriterion("externalid not between", value1, value2, "externalid");
            return (Criteria) this;
        }

        public Criteria andOldvalueIsNull() {
            addCriterion("oldvalue is null");
            return (Criteria) this;
        }

        public Criteria andOldvalueIsNotNull() {
            addCriterion("oldvalue is not null");
            return (Criteria) this;
        }

        public Criteria andOldvalueEqualTo(String value) {
            addCriterion("oldvalue =", value, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueNotEqualTo(String value) {
            addCriterion("oldvalue <>", value, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueGreaterThan(String value) {
            addCriterion("oldvalue >", value, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueGreaterThanOrEqualTo(String value) {
            addCriterion("oldvalue >=", value, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueLessThan(String value) {
            addCriterion("oldvalue <", value, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueLessThanOrEqualTo(String value) {
            addCriterion("oldvalue <=", value, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueLike(String value) {
            addCriterion("oldvalue like", value, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueNotLike(String value) {
            addCriterion("oldvalue not like", value, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueIn(List<String> values) {
            addCriterion("oldvalue in", values, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueNotIn(List<String> values) {
            addCriterion("oldvalue not in", values, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueBetween(String value1, String value2) {
            addCriterion("oldvalue between", value1, value2, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andOldvalueNotBetween(String value1, String value2) {
            addCriterion("oldvalue not between", value1, value2, "oldvalue");
            return (Criteria) this;
        }

        public Criteria andProcessidIsNull() {
            addCriterion("processid is null");
            return (Criteria) this;
        }

        public Criteria andProcessidIsNotNull() {
            addCriterion("processid is not null");
            return (Criteria) this;
        }

        public Criteria andProcessidEqualTo(String value) {
            addCriterion("processid =", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotEqualTo(String value) {
            addCriterion("processid <>", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidGreaterThan(String value) {
            addCriterion("processid >", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidGreaterThanOrEqualTo(String value) {
            addCriterion("processid >=", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLessThan(String value) {
            addCriterion("processid <", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLessThanOrEqualTo(String value) {
            addCriterion("processid <=", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLike(String value) {
            addCriterion("processid like", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotLike(String value) {
            addCriterion("processid not like", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidIn(List<String> values) {
            addCriterion("processid in", values, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotIn(List<String> values) {
            addCriterion("processid not in", values, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidBetween(String value1, String value2) {
            addCriterion("processid between", value1, value2, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotBetween(String value1, String value2) {
            addCriterion("processid not between", value1, value2, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidIsNull() {
            addCriterion("processinstanceid is null");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidIsNotNull() {
            addCriterion("processinstanceid is not null");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidEqualTo(Long value) {
            addCriterion("processinstanceid =", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidNotEqualTo(Long value) {
            addCriterion("processinstanceid <>", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidGreaterThan(Long value) {
            addCriterion("processinstanceid >", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidGreaterThanOrEqualTo(Long value) {
            addCriterion("processinstanceid >=", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidLessThan(Long value) {
            addCriterion("processinstanceid <", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidLessThanOrEqualTo(Long value) {
            addCriterion("processinstanceid <=", value, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidIn(List<Long> values) {
            addCriterion("processinstanceid in", values, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidNotIn(List<Long> values) {
            addCriterion("processinstanceid not in", values, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidBetween(Long value1, Long value2) {
            addCriterion("processinstanceid between", value1, value2, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andProcessinstanceidNotBetween(Long value1, Long value2) {
            addCriterion("processinstanceid not between", value1, value2, "processinstanceid");
            return (Criteria) this;
        }

        public Criteria andValueIsNull() {
            addCriterion("value is null");
            return (Criteria) this;
        }

        public Criteria andValueIsNotNull() {
            addCriterion("value is not null");
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(String value) {
            addCriterion("value =", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotEqualTo(String value) {
            addCriterion("value <>", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThan(String value) {
            addCriterion("value >", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(String value) {
            addCriterion("value >=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThan(String value) {
            addCriterion("value <", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThanOrEqualTo(String value) {
            addCriterion("value <=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLike(String value) {
            addCriterion("value like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotLike(String value) {
            addCriterion("value not like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueIn(List<String> values) {
            addCriterion("value in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotIn(List<String> values) {
            addCriterion("value not in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueBetween(String value1, String value2) {
            addCriterion("value between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotBetween(String value1, String value2) {
            addCriterion("value not between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andVariableidIsNull() {
            addCriterion("variableid is null");
            return (Criteria) this;
        }

        public Criteria andVariableidIsNotNull() {
            addCriterion("variableid is not null");
            return (Criteria) this;
        }

        public Criteria andVariableidEqualTo(String value) {
            addCriterion("variableid =", value, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidNotEqualTo(String value) {
            addCriterion("variableid <>", value, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidGreaterThan(String value) {
            addCriterion("variableid >", value, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidGreaterThanOrEqualTo(String value) {
            addCriterion("variableid >=", value, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidLessThan(String value) {
            addCriterion("variableid <", value, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidLessThanOrEqualTo(String value) {
            addCriterion("variableid <=", value, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidLike(String value) {
            addCriterion("variableid like", value, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidNotLike(String value) {
            addCriterion("variableid not like", value, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidIn(List<String> values) {
            addCriterion("variableid in", values, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidNotIn(List<String> values) {
            addCriterion("variableid not in", values, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidBetween(String value1, String value2) {
            addCriterion("variableid between", value1, value2, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableidNotBetween(String value1, String value2) {
            addCriterion("variableid not between", value1, value2, "variableid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidIsNull() {
            addCriterion("variableinstanceid is null");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidIsNotNull() {
            addCriterion("variableinstanceid is not null");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidEqualTo(String value) {
            addCriterion("variableinstanceid =", value, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidNotEqualTo(String value) {
            addCriterion("variableinstanceid <>", value, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidGreaterThan(String value) {
            addCriterion("variableinstanceid >", value, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidGreaterThanOrEqualTo(String value) {
            addCriterion("variableinstanceid >=", value, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidLessThan(String value) {
            addCriterion("variableinstanceid <", value, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidLessThanOrEqualTo(String value) {
            addCriterion("variableinstanceid <=", value, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidLike(String value) {
            addCriterion("variableinstanceid like", value, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidNotLike(String value) {
            addCriterion("variableinstanceid not like", value, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidIn(List<String> values) {
            addCriterion("variableinstanceid in", values, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidNotIn(List<String> values) {
            addCriterion("variableinstanceid not in", values, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidBetween(String value1, String value2) {
            addCriterion("variableinstanceid between", value1, value2, "variableinstanceid");
            return (Criteria) this;
        }

        public Criteria andVariableinstanceidNotBetween(String value1, String value2) {
            addCriterion("variableinstanceid not between", value1, value2, "variableinstanceid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 07 01:42:26 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}