package valpoSystems.emailTask.orm.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import valpoSystems.emailTask.orm.model.AuditTaskImpl;
import valpoSystems.emailTask.orm.model.AuditTaskImplExample;

public interface AuditTaskImplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    long countByExample(AuditTaskImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int deleteByExample(AuditTaskImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int insert(AuditTaskImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int insertSelective(AuditTaskImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    List<AuditTaskImpl> selectByExample(AuditTaskImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    AuditTaskImpl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int updateByExampleSelective(@Param("record") AuditTaskImpl record, @Param("example") AuditTaskImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int updateByExample(@Param("record") AuditTaskImpl record, @Param("example") AuditTaskImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int updateByPrimaryKeySelective(AuditTaskImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audittaskimpl
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int updateByPrimaryKey(AuditTaskImpl record);
}