package valpoSystems.emailTask.orm.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import valpoSystems.emailTask.orm.model.VariableInstanceLog;
import valpoSystems.emailTask.orm.model.VariableInstanceLogExample;

public interface VariableInstanceLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    long countByExample(VariableInstanceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int deleteByExample(VariableInstanceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int insert(VariableInstanceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int insertSelective(VariableInstanceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    List<VariableInstanceLog> selectByExample(VariableInstanceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    VariableInstanceLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int updateByExampleSelective(@Param("record") VariableInstanceLog record, @Param("example") VariableInstanceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int updateByExample(@Param("record") VariableInstanceLog record, @Param("example") VariableInstanceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int updateByPrimaryKeySelective(VariableInstanceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.variableinstancelog
     *
     * @mbg.generated Sat Jul 07 01:42:26 COT 2018
     */
    int updateByPrimaryKey(VariableInstanceLog record);
}